export interface SpriteDefinition {
  palette: Record<string, string>;
  grid: string[];
}

export const SPRITES = {
  hero: {
    palette: {
      H: '#3A2A1E',
      h: '#E8A24E',
      g: '#B8732C',
      s: '#FBD7B0',
      k: '#E0B287',
      t: '#3F8DBA',
      d: '#2A6B96',
      b: '#FFFFFF',
      l: '#5A3320',
      r: '#A33A2A',
      y: '#E8B85A',
      w: '#D9D2BE',
      n: '#7A5A3A',
      e: '#1F1F2C',
    },
    grid: [
      "................",
      ".....HhhhhH.....",
      "....HhggghhH....",
      "....HhgggghH....",
      "....Hhggggghh...",
      "...HsHhhhhsssH..",
      "...HseHHHesssH..",
      "...HsssssssssH..",
      "...HtttttttttH..",
      "...HtbttttbttH..",
      "...HttttttttHrr",
      "...HttdtttdtHry",
      "...HtttttttHHrr",
      "....HsHHHsHl....",
      "....HllHHllH....",
      ".....HHH.HHH....",
    ],
  },

  sword: {
    palette: {
      H: '#2A1F14',
      w: '#E6E1CC',
      g: '#B8B2A0',
      n: '#7A4A1E',
      y: '#E8B85A',
      r: '#A33A2A',
    },
    grid: [
      "................",
      "................",
      "..............HH",
      ".............HwH",
      "............HwgH",
      "...........HwgH.",
      "..........HwgH..",
      ".........HwgH...",
      "........HwgH....",
      ".......HwgH.....",
      "......HwgH......",
      "....HHHHHHHHH...",
      "....HynyrnyH....",
      "....HHnnnnnH....",
      ".....HnrnH......",
      "......HnH.......",
    ],
  },

  shield: {
    palette: {
      H: '#2A1F14',
      r: '#A33A2A',
      d: '#7A2818',
      y: '#E8B85A',
      g: '#A07028',
      w: '#FBE2A0',
      n: '#5A3320',
    },
    grid: [
      "................",
      "....HyyyyyyH....",
      "...HyywwwwgyH...",
      "..HyrrrrrrrdyH..",
      ".HyrrrdddrrrdyH.",
      ".HyrdyyyyydrryH.",
      "Hyrrdywwwgydrryw",
      "Hyrrdywyywgydrry",
      "Hyrrdyywygydrryw",
      "Hyrrdygggggdrryw",
      ".HyrdyyygyydrryH",
      ".HyrrrdgddrrrdyH",
      "..HyrrrrrrrdyH..",
      "...HyywwwgyyH...",
      "....HyyyyyyH....",
      "................",
    ],
  },

  lantern: {
    palette: {
      H: '#2A1F14',
      n: '#5A3320',
      m: '#3A2418',
      y: '#FFE08A',
      o: '#F0A040',
      a: '#FF6B2A',
      w: '#FFE6B0',
      k: '#1A1208',
    },
    grid: [
      ".......HnH......",
      ".......HnH......",
      "......HnnnH.....",
      ".....HnnnnnH....",
      ".....HnnnnnH....",
      "....HnyyoyynH...",
      "....HyywayoyH...",
      "....HyowwoaoH...",
      "....HyooaoooH...",
      "....HoyoyoyoH...",
      "....HyooyooyH...",
      "....HoyyoyyoH...",
      "....HnnnnnnnH...",
      ".....HnmmmnH....",
      ".....HnHHHnH....",
      "................",
    ],
  },

  scroll: {
    palette: {
      H: '#2A1F14',
      p: '#F4E4C1',
      s: '#D4BC92',
      r: '#A33A2A',
      d: '#7A2818',
      n: '#5A3320',
      i: '#3A2418',
    },
    grid: [
      "................",
      "...HHHHHHHHHHH..",
      "..HpppppppppppH.",
      ".HpsHHHHHHHHHsH.",
      ".HpsiiHHHHiiHsH.",
      ".HpsiHHHHHHiHsH.",
      ".HpsHHiiiiHHHsH.",
      "Hr.HsiHHHHiiHsH.",
      "Hd.HsHiiiiiHHsH.",
      "HrrHsiHHHHHHHsH.",
      "Hd.HsHHHHHHHHsH.",
      ".Hn.HHHHHHHHHsH.",
      "..HpppppppppppH.",
      "...HHHHHHHHHHH..",
      "................",
      "................",
    ],
  },

  chest: {
    palette: {
      H: '#2A1F14',
      n: '#7A4A1E',
      d: '#4A2E12',
      y: '#E8B85A',
      g: '#A07028',
      w: '#FBE2A0',
      s: '#FFE8A0',
    },
    grid: [
      "..............s.",
      ".............sss",
      "..............s.",
      ".....HHHHHHHH...",
      "....Hnnnnnnnnh..",
      "...HnyyyyyyyynH.",
      "..HnywwwwwwgynH.",
      "..HyyyyyyyyyyyH.",
      "..HnnnHyyyHnnnH.",
      "..HnnnHyHyHnnnH.",
      "..HnddHyHyHnddH.",
      "..HnddyyyyyHddH.",
      "..HnddHwwwHddnH.",
      "..HnddHHHHHHddH.",
      "..HHHHHHHHHHHHH.",
      "................",
    ],
  },

  heart: {
    palette: {
      H: '#2A1F14',
      r: '#E84852',
      d: '#A02830',
      w: '#FFB0B8',
    },
    grid: [
      "................",
      "...HHH....HHH...",
      "..HrrrH..HrrrH..",
      ".HrwrrrHHrrrrH..",
      ".HrwrrrrrrrrdH..",
      ".HrwrrrrrrrrdH..",
      ".HrrrrrrrrrrdH..",
      ".HrrrrrrrrrdH...",
      "..HrrrrrrrrdH...",
      "..HdrrrrrrdH....",
      "...HdrrrrrdH....",
      "....HdrrrdH.....",
      ".....HdrdH......",
      "......HdH.......",
      "................",
      "................",
    ],
  },

  heartEmpty: {
    palette: { H: '#8A7B66', w: '#F4ECDF' },
    grid: [
      "................",
      "...HHH....HHH...",
      "..HwwwH..HwwwH..",
      ".HwwwwwHHwwwwH..",
      ".HwwwwwwwwwwwH..",
      ".HwwwwwwwwwwwH..",
      ".HwwwwwwwwwwwH..",
      ".HwwwwwwwwwwH...",
      "..HwwwwwwwwwH...",
      "..HwwwwwwwwH....",
      "...HwwwwwwwH....",
      "....HwwwwwH.....",
      ".....HwwwH......",
      "......HwH.......",
      "................",
      "................",
    ],
  },

  star: {
    palette: {
      H: '#3A2A18',
      y: '#FFD24A',
      o: '#E89020',
      w: '#FFEFB0',
    },
    grid: [
      "................",
      ".......HH.......",
      "......HwyH......",
      "......HyyH......",
      "...HHHHwyHHHH...",
      "..HyywwyywyyyH..",
      "..HwywyyyyyooH..",
      "...HyyyyyyyoH...",
      "....HyyyyyyoH...",
      "...HyyHHHHyyoH..",
      "..HyyHH..HHyooH.",
      ".HwyHH....HHyoH.",
      ".HHH.......HHHH.",
      "................",
      "................",
      "................",
    ],
  },

  potion: {
    palette: {
      H: '#2A1F14',
      n: '#7A4A1E',
      g: '#3FA85F',
      d: '#1F6838',
      w: '#A8E8C0',
      l: '#D9D2BE',
    },
    grid: [
      "................",
      ".....HnnnnH.....",
      ".....HnnnnH.....",
      "....HHnnnnHH....",
      "....HllllllH....",
      "....HlggggdH....",
      "...HHgwgggdgHH..",
      "..HgwwgggggdgH..",
      "..HggwgggdgggH..",
      "..HgwggggdggdH..",
      "..HggwgggggdgH..",
      "...HgggggdggH...",
      "....HHgggggH....",
      ".....HHHHHHH....",
      "................",
      "................",
    ],
  },

  d20: {
    palette: {
      H: '#2A1F14',
      p: '#7A5AC8',
      d: '#4A3088',
      w: '#C0A8E8',
      y: '#FFD24A',
    },
    grid: [
      ".......HH.......",
      ".....HHwwHH.....",
      "....HwwppwwH....",
      "...HwppppppwH...",
      "..HwppppppppwH..",
      ".HwppdppppdppwH.",
      ".HpppyyHHyyypdH.",
      ".HppdyHpHpHydpH.",
      ".HpppyyypHHydpH.",
      ".HppdpyHHHyypdH.",
      ".HppppdyyyypppH.",
      "..HppppdpppppdH.",
      "...HppppdpppdH..",
      "....HpppdpdpH...",
      ".....HHpdpHH....",
      ".......HHH......",
    ],
  },

  mushroom: {
    palette: {
      H: '#2A1F14',
      r: '#D8443A',
      d: '#8A2820',
      w: '#FBF5EA',
      s: '#D9CCAA',
      n: '#A07A4A',
    },
    grid: [
      "................",
      "....HHHHHH......",
      "...HrrrrrrH.....",
      "..HrwrrrrrrH....",
      "..HrwwrrwrrdH...",
      ".HrrrrwwrrrrdH..",
      ".HrrrwwwrrrrrdH.",
      ".HrrrrrwrrrrrdH.",
      ".HddddddddddddH.",
      "..HwwwwwwwwwwH..",
      "...HsswwwwssH...",
      "....HsswwsnH....",
      "....HnssssnH....",
      "....HnnnnnnH....",
      ".....HHHHH......",
      "................",
    ],
  },

  tree: {
    palette: {
      H: '#2A1F14',
      g: '#5AA84A',
      d: '#2E6A2A',
      l: '#9BD060',
      n: '#5A3320',
      m: '#3A1F12',
    },
    grid: [
      ".....HHHHHH.....",
      "....HglglglH....",
      "...HglgggglgH...",
      "..HglgddgglglH..",
      "..HglgdgglglgH..",
      ".HglgggldgglglH.",
      ".HgldglgldgglgH.",
      "..HglgggdgglgH..",
      "..HglddglgglgH..",
      "...HglgggglgH...",
      "....HglglglH....",
      ".....HHnHHH.....",
      ".....HnmnH......",
      ".....HnmnH......",
      ".....HHHHH......",
      "................",
    ],
  },

  compass: {
    palette: {
      H: '#2A1F14',
      y: '#E8B85A',
      g: '#A07028',
      w: '#F4ECDF',
      r: '#D8443A',
      d: '#7A2818',
      k: '#3A2A18',
    },
    grid: [
      "................",
      "....HyyyyyyH....",
      "...HygggggggH...",
      "..HyywwwwwwgyH..",
      "..HygwHHHHHwgH..",
      ".HygwHrrrrrHwgH.",
      ".HygwHrrwHHHwgH.",
      ".HygwHrwHHHHwgH.",
      ".HygwHkHHHddwgH.",
      ".HygwHHHHddwwgH.",
      ".HygwHHHddrwwgH.",
      "..HygwHHHHHwgH..",
      "..HyygggggggyH..",
      "...HyyyyyyyyH...",
      "....HyyyyyyH....",
      "................",
    ],
  },

  crown: {
    palette: {
      H: '#2A1F14',
      y: '#E8B85A',
      g: '#A07028',
      w: '#FBE2A0',
      r: '#D8443A',
      b: '#3F8DBA',
    },
    grid: [
      "..H...........H.",
      "..H...........H.",
      "..H..H.....H..H.",
      "..HyyHyyHyyHyyH.",
      ".HyyywHyyyHwyyyH",
      ".HygyrygyygbyygH",
      ".HygggggggggggH.",
      ".HygggHHgHHgggH.",
      ".HHHHHHHHHHHHHH.",
      "................",
    ],
  },

  key: {
    palette: {
      H: '#2A1F14',
      y: '#E8B85A',
      g: '#A07028',
      w: '#FBE2A0',
      r: '#D8443A',
    },
    grid: [
      "................",
      "................",
      ".....HHHH.......",
      "....HywwyH......",
      "...HywrrwyH.....",
      "...HywHHwyH.....",
      "....HyrrwyH.....",
      ".....HyyyyHHHHH.",
      "......HyHyyyyyH.",
      "......HyHHHHHHH.",
      "......HyyH......",
      "......HyyHHH....",
      "......HyHHyH....",
      "......HyyyyH....",
      ".......HHHH.....",
      "................",
    ],
  },

  coin: {
    palette: {
      H: '#2A1F14',
      y: '#E8B85A',
      g: '#A07028',
      w: '#FBE2A0',
    },
    grid: [
      "................",
      "....HHHHHHH.....",
      "...HywwwwwgH....",
      "..HywyyyyygyH...",
      "..HwyyyHyyygyH..",
      ".HwygyHHHygggH..",
      ".HwygHHyHHyggH..",
      ".HwygyyyyyyggH..",
      ".HwygHyyHHyggH..",
      ".HwygHyHHyyggH..",
      "..HygyyHyyyggH..",
      "..HygyyyyyyggH..",
      "...HyggggggH....",
      "....HHHHHHH.....",
      "................",
      "................",
    ],
  },

  sparkles: {
    palette: { H: '#3A2A18', y: '#FFD24A', w: '#FFEFB0' },
    grid: [
      "................",
      "..H..........H..",
      ".HyH........HyH.",
      "HyyyH......HwyH.",
      ".HyH........HyH.",
      "..H..........H..",
      ".......H........",
      "......HyH.......",
      ".....HyywH......",
      "......HyH.......",
      ".......H........",
      "..H..........H..",
      ".HyH........HyH.",
      "HyyyH......HwyH.",
      ".HyH........HyH.",
      "..H..........H..",
    ],
  },

  banner: {
    palette: {
      H: '#2A1F14',
      b: '#3F8DBA',
      d: '#2A6B96',
      y: '#E8B85A',
      w: '#A8D0E8',
      n: '#5A3320',
    },
    grid: [
      "..HnnnnnnnnnnH..",
      "..HyyyyyyyyyyH..",
      "..HbwwbbbbbbyH..",
      "..HbwbHHHHbbyH..",
      "..HbbbHwwHbbyH..",
      "..HbbbHwwHbbyH..",
      "..HbbdHHHHbdyH..",
      "..HbbbbbbbbbyH..",
      "..HyyyyyyyyyyH..",
      "..HbbbbbbbbbyH..",
      "..HbdddddddyH...",
      "...HbdddddyH....",
      "....HbdddyH.....",
      ".....HbdyH......",
      "......HyH.......",
      "......HHH.......",
    ],
  },

  eye: {
    palette: {
      H: '#2A1F14',
      w: '#FBF5EA',
      b: '#3F8DBA',
      d: '#1F4060',
      k: '#0A0810',
    },
    grid: [
      "................",
      "................",
      "....HHHHHHHH....",
      "..HHwwwwwwwwHH..",
      ".HwwwwwwwwwwwwH.",
      "HwwwHHbbbbHHwwwH",
      "HwwHbbdddbbHwwH.",
      "HwwHbdkkkdbHwwH.",
      "HwwHbdkkkdbHwwH.",
      "HwwHbbdddbbHwwH.",
      "HwwwHHbbbbHHwwH.",
      ".HwwwwwwwwwwwH..",
      "..HHwwwwwwwwHH..",
      "....HHHHHHHH....",
      "................",
      "................",
    ],
  },

  quill: {
    palette: {
      H: '#2A1F14',
      w: '#FBF5EA',
      g: '#D9D2BE',
      r: '#D8443A',
      n: '#5A3320',
      k: '#0A0810',
    },
    grid: [
      "............HHHH",
      "..........HHwwwH",
      ".........HwwggwH",
      "........HwwgwgwH",
      ".......HwwgwgwwH",
      "......HwwgwgwgwH",
      ".....HwwgwgwggwH",
      "....HwwgwgwgwwH.",
      "...HwwgwgwgwwH..",
      "..HwwgwgwgwwH...",
      ".HwwgwgwgwwH....",
      "HwwwgwggwwH.....",
      ".HwggwwwwH......",
      "..Hkk.HwH.......",
      "..Hkk...........",
      "................",
    ],
  },

  bird: {
    palette: {
      H: '#2A1F14',
      b: '#7A4A1E',
      d: '#4A2E12',
      l: '#C8A878',
      y: '#E8B85A',
      w: '#FBE2A0',
      e: '#0A0810',
    },
    grid: [
      "................",
      "................",
      "......HbbH......",
      ".....HblbbH.....",
      "....HbleHbbH....",
      "...HblllbbbbHHH.",
      "...HblllbbbdbbyH",
      "..HbllllbbdddbbH",
      "..Hbllllbbbdbbb.",
      "...HbllllbbbbH..",
      "....HbbblbbbH...",
      ".....HbbHbbH....",
      "......HH.HH.....",
      "......H..H......",
      "................",
      "................",
    ],
  },

  feather: {
    palette: {
      H: '#2A1F14',
      w: '#FBF5EA',
      g: '#D9D2BE',
      a: '#3F8DBA',
      d: '#2A6B96',
      n: '#5A3320',
    },
    grid: [
      "............HH..",
      "...........HwwH.",
      "..........HwawH.",
      ".........HwawaH.",
      "........HwawawH.",
      ".......HwawawaH.",
      "......HwawawawH.",
      ".....HwawadwawH.",
      "....HwawawawawH.",
      "...HwawadwawawH.",
      "..HwawawawawawH.",
      ".HwawawawawawH..",
      "HwadddddddwwH...",
      ".HwwwwH.HwH.....",
      "..HnH..HnH......",
      "..HnnH..........",
    ],
  },

  cards: {
    palette: { H: '#2A1F14', p: '#F4E4C1', s: '#D4BC92', r: '#D8443A' },
    grid: [
      "................",
      "..HHHHHHHHH.....",
      ".HppppppppHH....",
      ".HpsssssssspH...",
      ".HpsHHHHHHHspH..",
      ".HpsHHHHHHHspH..",
      ".HpsHHrrHHHspH..",
      ".HpsHrrrrHHspH..",
      ".HpsHHrrHHHspH..",
      ".HpsHHHHHHHspH..",
      ".HpssssssssspH..",
      ".HpppppppppppH..",
      "..HHHHHHHHHHHH..",
      "................",
      "................",
      "................",
    ],
  },

  grass: {
    palette: { g: '#7AB85A', d: '#4F8838', l: '#A8D870' },
    grid: [
      "ggggggggggggggg.",
      "gdggggldgglgggg.",
      "gggdgggggddgggg.",
      "ggldggggggggdgg.",
      "ggggggddgggggdg.",
      "gddggggggldgggg.",
      "gggggldgggggggg.",
      "ggdggggggggdggl.",
    ],
  },

  book: {
    palette: {
      H: '#2A1F14',
      l: '#7A2E1A',
      r: '#A33A2A',
      o: '#C4513A',
      y: '#E8B85A',
      g: '#B8862E',
      w: '#F4ECDF',
      d: '#C9BCA4',
      n: '#5A3320',
      s: '#A33A2A',
    },
    grid: [
      "................",
      "..HHHHHHHHHHHH..",
      ".HllllllllllllH.",
      ".HlrrrrrrrrrrlH.",
      ".HlroooooorrnlH.",
      ".HlroygggyorslH.",
      ".HlroyHwwHyorslH",
      ".HlroyHwwHyorslH",
      ".HlroyHwwHyorslH",
      ".HlroygggyorslH.",
      ".HlroooooorrnlH.",
      ".HlrrrrrrrrrrlH.",
      ".HllllllllllllH.",
      "..HHwdwdwdwdHH..",
      "....HwdwdwdH....",
      "................",
    ],
  },

  film: {
    palette: {
      H: '#2A1F14',
      k: '#1A1714',
      w: '#F4ECDF',
      g: '#8A7B66',
      y: '#E8B85A',
      r: '#A33A2A',
    },
    grid: [
      "................",
      "....HHHHHHHHHHH.",
      "...HwHkHwHkHwHk.",
      "..Hk.Hw.Hk.Hw.Hk",
      "..HHHHHHHHHHHHH.",
      "..HkkkkkkkkkkkH.",
      "..HkwwwwwwwwwkH.",
      "..HkwkkkkkkkwkH.",
      "..HkwkrrrrkkwkH.",
      "..HkwkrAArkkwkH.",
      "..HkwkrrrrkkwkH.",
      "..HkwkkkkkkkwkH.",
      "..HkwwwwwwwwwkH.",
      "..HkkkkkkkkkkkH.",
      "..HHHHHHHHHHHHH.",
      "................",
    ],
  },

  tv: {
    palette: {
      H: '#2A1F14',
      n: '#5A3320',
      w: '#7A4A1E',
      d: '#3A2418',
      s: '#3F8DBA',
      l: '#A8D0E8',
      k: '#1A1714',
      y: '#E8B85A',
    },
    grid: [
      ".......H...H....",
      "......Hy.Hy.....",
      ".....Hy.Hy......",
      "......HyHy......",
      ".......HH.......",
      ".HHHHHHHHHHHHHH.",
      ".HwwwwwwwwwwwwH.",
      ".HwHHHHHHHHHHwH.",
      ".HwHsssslssssHwH",
      ".HwHsAAslsssaHwH",
      ".HwHsAAsssssaHwH",
      ".HwHssslssssaHwH",
      ".HwHHHHHHHHHHwH.",
      ".HwddddwwddddwH.",
      ".HnnHHHHHHHHnnH.",
      "..HH..HH..HH..H.",
    ],
  },

  controller: {
    palette: {
      H: '#2A1F14',
      g: '#5A4A3A',
      l: '#7A6A5A',
      d: '#3A2A1E',
      k: '#1A1714',
      r: '#A33A2A',
      y: '#E8B85A',
      b: '#3F8DBA',
    },
    grid: [
      "................",
      "................",
      "..HHHHHHHHHHHH..",
      ".HglllllllllgH..",
      ".HglHHkkHHHkglH.",
      "HglkHkkkHkHkglH.",
      "HglHHkkHHHkglH..",
      "HgllllllllllgH..",
      "HglkkllllrybgH..",
      "HglllllllllgH...",
      ".HgllllllllgH...",
      ".HHgggggggHH....",
      "...HHHHHHH......",
      "................",
      "................",
      "................",
    ],
  },
} satisfies Record<string, SpriteDefinition>;

export type SpriteName = keyof typeof SPRITES;
